apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcorewebapptest-deployment
  labels:
    app: aspnetcorewebapptest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetcorewebapptest
  template:
    metadata:
      labels:
        app: aspnetcorewebapptest
    spec:
      containers:
        - name: aspnetcorewebapptest-server
          image: abdulkadirnacir/aspnetcorewebapptest:latest
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcorewebapptest-service
spec:
  selector:
    app: aspnetcorewebapptest
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 3001
      nodePort: 31111
