apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcorewebapptest-deployment
  labels:
    app: aspnetcorewebapptest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetcorewebapptest
  template:
    metadata:
      labels:
        app: aspnetcorewebapptest
    spec:
      containers:
        - name: aspnetcorewebapptest-server
          image: abdulkadirnacir/aspnetcorewebapptest:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcorewebapptest-service
spec:
  selector:
    app: aspnetcorewebapptest
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31112

